version: '3'

services:
    db:
        # restart: always
        image: postgres
        # ports:
        #     - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=Andyelp3648!
            - POSTGRES_USER=postgres
            - POSTGRES_DB=blog_db
            # - POSTGRES_PORT=5432

    web:
        build: .
        # command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/andrew/Documents/django/blog/docker
        ports:
            - "8000:8000"
        depends_on:
            - db
        # environment: 
        #     DATABASE_URL: postgres://postgres:Andyelp3648!@db:5432/porfolio_db
